version: '3.8'

services:
  #dynamodb:
  #  image: amazon/dynamodb-local
  #  container_name: dynamodb
  #  ports:
  #    - "8000:8000"
  #  command: "-jar DynamoDBLocal.jar -sharedDb"
  #  networks:
  #    - patient-net


  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - patient-net



  patient-service:
    build:
      context: ./patient_service
    container_name: patient-service
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb
    environment:
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      DYNAMODB_ENDPOINT_URL: http://dynamodb:8000
      PATIENTS_TABLE: Patients
    networks:
      - patient-net

networks:
  patient-net:
    driver: bridge